# Disable some built-in rules
config:
  no-inline-html: false
  MD013:
    code_block_line_length: 120
  MD024:
    allow_different_nesting: true
#  no-trailing-spaces: false
#  no-multiple-blanks: false

# Include a custom rule package
#customRules:
#  - markdownlint-rule-titlecase

# Fix any fixable errors
fix: false

# Define a custom front matter pattern
#frontMatter: "<head>[^]*<\/head>"

# Define glob expressions to ignore
ignores:
  - "*.autogen.md"

# Use a plugin to recognize math
#markdownItPlugins:
#  -
#    - "@iktakahiro/markdown-it-katex"

# Disable inline config comments
noInlineConfig: true

# Disable progress on stdout
noProgress: true

# Use a specific formatter
outputFormatters:
  -
    - markdownlint-cli2-formatter-default
